/* automatically generated by rust-bindgen 0.56.0 */

pub const NRDEFFILES: u32 = 10;
extern "C" {
    pub static mut gargc: ::std::os::raw::c_int;
}
extern "C" {
    pub static mut gargv: *mut *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn LoadFile(filename: *const ::std::os::raw::c_char);
}
extern "C" {
    pub fn SetEnvValues(force: ::std::os::raw::c_int);
}
extern "C" {
    pub fn ProcessArgs();
}
extern "C" {
    pub fn SetupConfigs();
}
