/* automatically generated by rust-bindgen 0.56.0 */

extern "C" {
    pub fn FilterFoldedBinsBlob(
        folded: *mut f32,
        bins: ::std::os::raw::c_int,
        strength: f32,
        iter: ::std::os::raw::c_int,
    );
}
